# Generated by Django 2.0.13 on 2019-03-28 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin?')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_pk', models.PositiveIntegerField()),
                ('remind_me', models.BooleanField(verbose_name='Remind me')),
                ('collection_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'core'), ('model', 'Collection')), models.Q(('app_label', 'core'), ('model', 'MetaCollection')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
        ),
    ]
