# Generated by Django 2.0.13 on 2019-04-03 07:48

from django.db import migrations, models
import django.utils.timezone
import markdownx.models
import talks_tue.revisions.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Description')),
                ('is_meta', models.BooleanField(default=False, verbose_name='Is metacollection?')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
            },
            bases=(talks_tue.revisions.utils.HasRevision, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Talk title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Talk description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talk date')),
                ('name', models.CharField(max_length=128, verbose_name="Speaker's name")),
                ('about_me', markdownx.models.MarkdownxField(max_length=512, verbose_name="Speaker's about me")),
                ('collections', models.ManyToManyField(blank=True, limit_choices_to={'is_meta': False}, related_name='talks', to='core.Collection', verbose_name='Collections')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_talk', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
                'ordering': ['timestamp'],
            },
            bases=(talks_tue.revisions.utils.HasRevision, models.Model),
        ),
    ]
