# Generated by Django 2.0.13 on 2019-04-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='edited_collections', to=settings.AUTH_USER_MODEL, verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='collection',
            name='meta_collections',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_meta': True}, related_name='sub_collections', to='core.Collection', verbose_name='Metacollections'),
        ),
        migrations.AddField(
            model_name='collection',
            name='organizer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_collections', to=settings.AUTH_USER_MODEL, verbose_name='Organizer'),
        ),
    ]
