# Generated by Django 2.0.13 on 2019-03-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190326_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_meta',
            field=models.BooleanField(default=False, verbose_name='Is metacollection?'),
        ),
        migrations.AddField(
            model_name='collection',
            name='sub_collections',
            field=models.ManyToManyField(blank=True, null=True, related_name='meta_collections', to='core.Collection', verbose_name='Subcollections'),
        ),
        migrations.AddField(
            model_name='historicalcollection',
            name='is_meta',
            field=models.BooleanField(default=False, verbose_name='Is metacollection?'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='talks',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='core.Talk', verbose_name='Talks'),
        ),
    ]
