# Generated by Django 2.0.13 on 2019-04-03 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Description')),
                ('is_meta', models.BooleanField(default=False, verbose_name='Is metacollection?')),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'create'), (1, 'change'), (2, 'delete')], default=1, verbose_name='Revision action')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'Collection revision',
                'verbose_name_plural': 'Collection revisions',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Talk title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Talk description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talk date')),
                ('name', models.CharField(max_length=128, verbose_name="Speaker's name")),
                ('about_me', markdownx.models.MarkdownxField(max_length=512, verbose_name="Speaker's about me")),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'create'), (1, 'change'), (2, 'delete')], default=1, verbose_name='Revision action')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('collections', models.ManyToManyField(blank=True, limit_choices_to={'is_meta': False}, related_name='talkrevisions', to='core.Collection', verbose_name='Collections')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.Talk', verbose_name='Original')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_talkrevision', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Talk revision',
                'verbose_name_plural': 'Talk revisions',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
