# Generated by Django 2.0.13 on 2019-03-30 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Description')),
                ('is_meta', models.BooleanField(default=False, verbose_name='Is metacollection?')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_collectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Editors')),
                ('meta_collections', models.ManyToManyField(blank=True, related_name='sub_collectionrevisions', to='core.MetaCollection', verbose_name='Metacollections')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_collectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Oragnizer')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.Collection', verbose_name='Original')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectionrevision_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaCollectionRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Description')),
                ('is_meta', models.BooleanField(default=False, verbose_name='Is metacollection?')),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('editors', models.ManyToManyField(blank=True, related_name='edited_metacollectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Editors')),
                ('meta_collections', models.ManyToManyField(blank=True, related_name='sub_metacollectionrevisions', to='core.MetaCollection', verbose_name='Metacollections')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_metacollectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Oragnizer')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.MetaCollection', verbose_name='Original')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metacollectionrevision_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TalkRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Talk title')),
                ('description', markdownx.models.MarkdownxField(max_length=512, verbose_name='Talk description')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Talk date')),
                ('name', models.CharField(max_length=128, verbose_name="Speaker's name")),
                ('about_me', markdownx.models.MarkdownxField(max_length=512, verbose_name="Speaker's about me")),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('collections', models.ManyToManyField(blank=True, related_name='collected_talkrevisions', to='core.Collection', verbose_name='Collections')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.Talk', verbose_name='Original')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_talkrevision', to='core.Tag', verbose_name='Tags')),
                ('user', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkrevision_actions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
