# Generated by Django 2.0.13 on 2019-04-02 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190402_0707'),
        ('revisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talkrevision',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkrevision_actions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='editors',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='edited_collectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='meta_collections',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_meta': True}, related_name='sub_collectionrevisions', to='core.Collection', verbose_name='Metacollections'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='organizer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_collectionrevisions', to=settings.AUTH_USER_MODEL, verbose_name='Oragnizer'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.Collection', verbose_name='Original'),
        ),
        migrations.AddField(
            model_name='collectionrevision',
            name='user',
            field=django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectionrevision_actions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
